### ISSUE TITLE
Interface small edits

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#80]
- [x] Bulk edit: remove selection from thumbnails after Save
- [x] Date facet: reset with the main 'clear'; at the moment needs a refresh to reset
- [x] Comp&feat facet: move above the 'Component' facet
- [x] clear url in Search after hitting 'clear' on facets

@geoffroy-noel-ddh I've added these in one issue, since they are small fixes and intreface only related. Let me know if this works for you, I can also split them.

**Comment by simonastoyanova** [comment]
Sorry, another one which I forgot to mention - again, I can put it in a separate issue if that's better.

When I'm in the Variant types part of the Defitions tab and refresh to see the new types I have added, the page always resets to the Latin1 defititions tab. Could it stay where it was after a refresh?

**Comment by geoffroy-noel-ddh** [comment]
All of these items should be addressed now.

Note that the first one was already working as desired. Saving changes on the search page already deselected all annotations. I've changed it so it also deselects all the tags.

Let me know if all works as expected now.

**Comment by simonastoyanova** [comment]
Thank you!
The url reset doesn't seem to be working, I tried both hitting 'Clear' and a hard refresh. I still see https://kingsdigitallab.github.io/crossreads/search.html?obj=http%3A%2F%2Fsicily.classics.ox.ac.uk%2Finscription%2FISic000827&img=ISic000827.jpg&q= 

Everything else is working.

**Comment by geoffroy-noel-ddh** [comment]
Hi Simona, those arguments in the query string don't set any parameters on the search interface (unless there's a bug I'm not aware of). They are kept there to keep the context from the annotation tab you came from. So if you click on the annotation tab the last inscriptions and image will be selected again.

I can remove all arguments when you click clear if you like. I'm just wondering if you notice any difference on the search between those two URLs:

https://kingsdigitallab.github.io/crossreads/search.html?obj=http%3A%2F%2Fsicily.classics.ox.ac.uk%2Finscription%2FISic000827&img=ISic000827.jpg&q=

https://kingsdigitallab.github.io/crossreads/search.html?q=

**Comment by simonastoyanova** [comment]
Hm, I'm not sure I need the context from the annotator tab preserved in the search. My usual workflow is to keep the three tabs open (annotator, definitions, search) and flick between them as needed. Mostly the annotator and the search. The search I use for queries across the corpus most of the time, very rarely for a single inscription. If I need to look at a single inscription, I type its ISic number in the Keywords field. So before today I haven't used the context of the annotator for the search. I did just now and it works as you've set it up, but I wouldn't be closing the search tab after every query only to open it again when I move to the next inscription in the annotator. Shall we discuss this tomorrow? I can show you how I use it and it might be easier to talk it over while screensharing.

I didn't notice any difference between the two URLs from above. If I've missed something, let me know, I'll try it.

**Comment by simonastoyanova** [comment]
That sounds good, thank you. 
I don't have other requests right now, the main thing left from the previous list is squishing the facets for space. I'll check all my notes and we'll see what comes up at the meeting tomorrow.

**Comment by geoffroy-noel-ddh** [comment]
Cool, I'm on the squishing case right now! Should be with you tomorrow.

**Comment by simonastoyanova** [comment]
Perfect! I'm just annotating today, won't be using the search this evening.

**Comment by geoffroy-noel-ddh** [comment]
Now a click on the search tab will no longer filter the search by the inscription selected on the annotation tab.

I've moved that link above the image on the annotator screen (see 'Image [and annotations]') so it is an active and optional choice rather than a default.

**Comment by simonastoyanova** [comment]
Great, thank you!
